### ISSUE TITLE
Add the ability to select electrodes on bank 1 and 2

### ISSUE THREAD

**Issue by jsiegle** [open-ephys/neuropixels-pxi#1]
Currently, this plugin only allows users to record from the 384 electrodes in bank 0. We need to add a button to enable electrodes on banks 1 and 2, which would disable the corresponding electrodes in the unselected banks. The selected configuration needs to be tracked in the settings file, and re-loaded on startup.

**Comment by medengineer** [comment]
Added w/ PR #6
