### ISSUE TITLE
Move probe configuration steps to a separate thread

### ISSUE THREAD

**Issue by jsiegle** [open-ephys/neuropixels-pxi#2]
There are a number of probe configuration steps, such as initializing gain settings and performing calibration, that block UI inputs while they occur. This can be confusing for users, especially when there are many probes connected. Moving these to a separate thread would make things much smoother. Ideally, there should be some visual feedback when these steps complete, e.g. making the probe icon change color.

**Comment by medengineer** [comment]
Added w/ PR #6
