### ISSUE TITLE
Add interface for configuring sync port

### ISSUE THREAD

**Issue by jsiegle** [open-ephys/neuropixels-pxi#4]
Currently, the leftmost PXI module provides the sync for all other modules, and it is configured as an "input."

We need an interface that allow users to select which module to use for synchronization (probably a ComboBox). The selected module can be configured as an input or an output (with a toggle switch). If it's an output, the frequency needs to be selected (ComboBox with 1.0 s as the default).

This interface should reside to the right of the PXI modules in the NeuropixEditor.

**Comment by medengineer** [comment]
Added w/ PR #6
