### ISSUE TITLE
Tailored to Adlink?

### ISSUE THREAD

**Issue by AGenews** [open-ephys/neuropixels-pxi#9]
Dear Josh + Team,
we were setting up our Neúropixels setup using the Adlink PXES-2301 and the PXI-PCIe8638 card and the neuropixels-pxi was working just out of the box for Windows 10. Now I'd like to have some more analog/digital input channels and my question now would be: Have you tailored the neuropixels-pxi version somehow also for Adlink which makes our setup work, or are the NI and Adlink devices similar enough to support both systems, and if yes would this mean I can simply use Adlink I/O DAQ cards with the NIDAQmx module?
Best and many thanks,
Andreas

**Comment by medengineer** [comment]
Hi Andreas,

We plan on supporting Adlink and will place an order for the PXES-2301 and the PXI-PCIe8638 card to begin development very soon. The NIDAQmx module uses National Instruments specific drivers so we will develop a separate module for Adlink. However, it will be analogous in functionality to the NIDAQmx plugin and should work just as well with Neuropixels. Thanks!

**Comment by AGenews** [comment]
Well as I said ... it works out of the box with the PXES-2301 and the PXI-PCIe8638 ... my question was why ;)

**Comment by medengineer** [comment]
Oh wow, you meant the Adlink card was working with the NIDAQmx module and you could see the analog/digital signals coming in? If so, that is quite surprising, I too am curious as to why! I'll have to look into this and get back to you. 

And yes, the NIDAQmx module works the same with PCIe NI cards mounted directly to the PC. We have tested and used the PCIe-6321.

**Comment by AGenews** [comment]
Dear medengineer,
I'd like to apologize for the misunderstanding. I only tested the PXI chassis from Adlink consisting of the PXES-2301 and the respective PCIe-PXI-8638 card and I could run the Neuropixels without any problem. Regarding the PCIe-6321 I am glad to hear it is working. Thank you very much!

**Comment by jsiegle** [comment]
Just to clarify...IMEC's Neuropixels API is independent of any PXI controller + chassis, so as long as you have the correct drivers installed the Neuropix-PXI plugin should work out of the box. The auxiliary analog + digital inputs use a separate API, however, so we'll have to make a new plugin to support Adlink cards. Is there a specific Adlink I/O card you have or are considering buying?

**Comment by AGenews** [comment]
Dear Josh, dear Pavel,
thanks a lot for the clarification. From the specs I would guess the Adlink PXI-2020 would be the most interesting card for us.
Best & Many Thanks!
Andreas
